kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: unifi-data-pvc
  labels:
    app: unifi
    release: latest

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
